const BIBLE_API_BASE = "https://bible.fhl.net/json";

// 完整 66 卷資料：書名、查詢縮寫、章數、英文全名。
const bibleMeta = [
    { bid: 1,  name: "創世記",         abbr: "創",   chapters: 50,  engName: "Genesis" },
    { bid: 2,  name: "出埃及記",       abbr: "出",   chapters: 40,  engName: "Exodus" },
    { bid: 3,  name: "利未記",         abbr: "利",   chapters: 27,  engName: "Leviticus" },
    { bid: 4,  name: "民數記",         abbr: "民",   chapters: 36,  engName: "Numbers" },
    { bid: 5,  name: "申命記",         abbr: "申",   chapters: 34,  engName: "Deuteronomy" },
    { bid: 6,  name: "約書亞記",       abbr: "書",   chapters: 24,  engName: "Joshua" },
    { bid: 7,  name: "士師記",         abbr: "士",   chapters: 21,  engName: "Judges" },
    { bid: 8,  name: "路得記",         abbr: "得",   chapters: 4,   engName: "Ruth" },
    { bid: 9,  name: "撒母耳記上",     abbr: "撒上", chapters: 31,  engName: "1 Samuel" },
    { bid: 10, name: "撒母耳記下",     abbr: "撒下", chapters: 24,  engName: "2 Samuel" },
    { bid: 11, name: "列王紀上",       abbr: "王上", chapters: 22,  engName: "1 Kings" },
    { bid: 12, name: "列王紀下",       abbr: "王下", chapters: 25,  engName: "2 Kings" },
    { bid: 13, name: "歷代志上",       abbr: "代上", chapters: 29,  engName: "1 Chronicles" },
    { bid: 14, name: "歷代志下",       abbr: "代下", chapters: 36,  engName: "2 Chronicles" },
    { bid: 15, name: "以斯拉記",       abbr: "拉",   chapters: 10,  engName: "Ezra" },
    { bid: 16, name: "尼希米記",       abbr: "尼",   chapters: 13,  engName: "Nehemiah" },
    { bid: 17, name: "以斯帖記",       abbr: "斯",   chapters: 10,  engName: "Esther" },
    { bid: 18, name: "約伯記",         abbr: "伯",   chapters: 42,  engName: "Job" },
    { bid: 19, name: "詩篇",           abbr: "詩",   chapters: 150, engName: "Psalms" },
    { bid: 20, name: "箴言",           abbr: "箴",   chapters: 31,  engName: "Proverbs" },
    { bid: 21, name: "傳道書",         abbr: "傳",   chapters: 12,  engName: "Ecclesiastes" },
    { bid: 22, name: "雅歌",           abbr: "歌",   chapters: 8,   engName: "Song of Solomon" },
    { bid: 23, name: "以賽亞書",       abbr: "賽",   chapters: 66,  engName: "Isaiah" },
    { bid: 24, name: "耶利米書",       abbr: "耶",   chapters: 52,  engName: "Jeremiah" },
    { bid: 25, name: "耶利米哀歌",     abbr: "哀",   chapters: 5,   engName: "Lamentations" },
    { bid: 26, name: "以西結書",       abbr: "結",   chapters: 48,  engName: "Ezekiel" },
    { bid: 27, name: "但以理書",       abbr: "但",   chapters: 12,  engName: "Daniel" },
    { bid: 28, name: "何西阿書",       abbr: "何",   chapters: 14,  engName: "Hosea" },
    { bid: 29, name: "約珥書",         abbr: "珥",   chapters: 3,   engName: "Joel" },
    { bid: 30, name: "阿摩司書",       abbr: "摩",   chapters: 9,   engName: "Amos" },
    { bid: 31, name: "俄巴底亞書",     abbr: "俄",   chapters: 1,   engName: "Obadiah" },
    { bid: 32, name: "約拿書",         abbr: "拿",   chapters: 4,   engName: "Jonah" },
    { bid: 33, name: "彌迦書",         abbr: "彌",   chapters: 7,   engName: "Micah" },
    { bid: 34, name: "那鴻書",         abbr: "鴻",   chapters: 3,   engName: "Nahum" },
    { bid: 35, name: "哈巴谷書",       abbr: "哈",   chapters: 3,   engName: "Habakkuk" },
    { bid: 36, name: "西番雅書",       abbr: "番",   chapters: 3,   engName: "Zephaniah" },
    { bid: 37, name: "哈該書",         abbr: "該",   chapters: 2,   engName: "Haggai" },
    { bid: 38, name: "撒迦利亞書",     abbr: "亞",   chapters: 14,  engName: "Zechariah" },
    { bid: 39, name: "瑪拉基書",       abbr: "瑪",   chapters: 4,   engName: "Malachi" },
    { bid: 40, name: "馬太福音",       abbr: "太",   chapters: 28,  engName: "Matthew" },
    { bid: 41, name: "馬可福音",       abbr: "可",   chapters: 16,  engName: "Mark" },
    { bid: 42, name: "路加福音",       abbr: "路",   chapters: 24,  engName: "Luke" },
    { bid: 43, name: "約翰福音",       abbr: "約",   chapters: 21,  engName: "John" },
    { bid: 44, name: "使徒行傳",       abbr: "徒",   chapters: 28,  engName: "Acts" },
    { bid: 45, name: "羅馬書",         abbr: "羅",   chapters: 16,  engName: "Romans" },
    { bid: 46, name: "哥林多前書",     abbr: "林前", chapters: 16,  engName: "1 Corinthians" },
    { bid: 47, name: "哥林多後書",     abbr: "林後", chapters: 13,  engName: "2 Corinthians" },
    { bid: 48, name: "加拉太書",       abbr: "加",   chapters: 6,   engName: "Galatians" },
    { bid: 49, name: "以弗所書",       abbr: "弗",   chapters: 6,   engName: "Ephesians" },
    { bid: 50, name: "腓立比書",       abbr: "腓",   chapters: 4,   engName: "Philippians" },
    { bid: 51, name: "歌羅西書",       abbr: "西",   chapters: 4,   engName: "Colossians" },
    { bid: 52, name: "帖撒羅尼迦前書", abbr: "帖前", chapters: 5,   engName: "1 Thessalonians" },
    { bid: 53, name: "帖撒羅尼迦後書", abbr: "帖後", chapters: 3,   engName: "2 Thessalonians" },
    { bid: 54, name: "提摩太前書",     abbr: "提前", chapters: 6,   engName: "1 Timothy" },
    { bid: 55, name: "提摩太後書",     abbr: "提後", chapters: 4,   engName: "2 Timothy" },
    { bid: 56, name: "提多書",         abbr: "多",   chapters: 3,   engName: "Titus" },
    { bid: 57, name: "腓利門書",       abbr: "門",   chapters: 1,   engName: "Philemon" },
    { bid: 58, name: "希伯來書",       abbr: "來",   chapters: 13,  engName: "Hebrews" },
    { bid: 59, name: "雅各書",         abbr: "雅",   chapters: 5,   engName: "James" },
    { bid: 60, name: "彼得前書",       abbr: "彼前", chapters: 5,   engName: "1 Peter" },
    { bid: 61, name: "彼得後書",       abbr: "彼後", chapters: 3,   engName: "2 Peter" },
    { bid: 62, name: "約翰一書",       abbr: "約一", chapters: 5,   engName: "1 John" },
    { bid: 63, name: "約翰二書",       abbr: "約二", chapters: 1,   engName: "2 John" },
    { bid: 64, name: "約翰三書",       abbr: "約三", chapters: 1,   engName: "3 John" },
    { bid: 65, name: "猶大書",         abbr: "猶",   chapters: 1,   engName: "Jude" },
    { bid: 66, name: "啟示錄",         abbr: "啟",   chapters: 22,  engName: "Revelation" }
];
